export const gamesData = [
  {
    id: 1,
    title: "Resident Evil Village",
    developer: "Capcom",
    publisher: "Capcom",
    releaseDate: "2024-05-09",
    genre: ["Horror", "Action", "Survival"],
    platform: ["PC", "PlayStation 5", "Xbox Series X"],
    rating: 4.7,
    description:
      "Experience survival horror like never before in the eighth major installment in the Resident Evil franchise. Set a few years after the biological disaster in Raccoon City, the story of Ethan Winter begins in Eastern Europe.",
    coverImage: "/resident-evil-village-game-cover.jpg",
    screenshots: [
      "/resident-evil-village-screenshot-1.jpg",
      "/resident-evil-village-screenshot-2.jpg",
      "/resident-evil-village-screenshot-3.jpg",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    status: "pending",
    submittedDate: "2024-10-15",
    fileSize: "60.2 GB",
    price: "499.000đ",
    minimumRequirements: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i7-8700K",
      memory: "16 GB RAM",
      graphics: "NVIDIA RTX 2070",
      storage: "70 GB SSD",
    },
  },
  {
    id: 2,
    title: "Hollow Knight",
    developer: "Team Cherry",
    publisher: "Team Cherry",
    releaseDate: "2017-02-24",
    genre: ["Metroidvania", "Action", "Adventure"],
    platform: ["PC", "Nintendo Switch", "PlayStation 4"],
    rating: 4.9,
    description:
      "Hollow Knight is a challenging 2D action-adventure of epic proportions. Explore a vast, atmospheric world full of mystery and danger. Hack and slash your way through a kingdom of insects.",
    coverImage: "/hollow-knight-game-cover.jpg",
    screenshots: [
      "/hollow-knight-screenshot-1.jpg",
      "/hollow-knight-screenshot-2.jpg",
      "/hollow-knight-screenshot-3.jpg",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    status: "pending",
    submittedDate: "2024-10-10",
    fileSize: "3.5 GB",
    price: "149.000đ",
    minimumRequirements: {
      os: "Windows 7 64-bit",
      processor: "Intel Core i5-6600K",
      memory: "8 GB RAM",
      graphics: "NVIDIA GTX 960",
      storage: "5 GB SSD",
    },
  },
  {
    id: 3,
    title: "Cyberpunk Nexus",
    developer: "Neon Studios",
    publisher: "Digital Dreams Inc",
    releaseDate: "2024-12-15",
    genre: ["Action", "RPG", "Sci-Fi"],
    platform: ["PC", "PlayStation 5", "Xbox Series X"],
    rating: 4.8,
    description:
      "Immerse yourself in a dystopian future where technology and humanity collide. Cyberpunk Nexus offers an expansive open world filled with intricate storylines, cutting-edge combat mechanics, and unforgettable characters.",
    coverImage: "/cyberpunk-nexus-game-cover.jpg",
    screenshots: [
      "/cyberpunk-nexus-screenshot-1.jpg",
      "/cyberpunk-nexus-screenshot-2.jpg",
      "/cyberpunk-nexus-screenshot-3.jpg",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    status: "approved",
    submittedDate: "2024-10-20",
    fileSize: "85.4 GB",
    price: "599.000đ",
    minimumRequirements: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i7-9700K",
      memory: "16 GB RAM",
      graphics: "NVIDIA RTX 2080",
      storage: "100 GB SSD",
    },
  },
  {
    id: 4,
    title: "Elden Ring",
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    releaseDate: "2022-02-25",
    genre: ["Action", "RPG", "Open World"],
    platform: ["PC", "PlayStation 5", "Xbox Series X"],
    rating: 4.9,
    description:
      "Journey through the Lands Between in this open-world masterpiece by FromSoftware. Explore vast fields, daunting dungeons, and fight fearsome bosses to restore the Elden Ring.",
    coverImage: "/elden-ring-game-cover.jpg",
    screenshots: [
      "/elden-ring-screenshot-1.jpg",
      "/elden-ring-screenshot-2.jpg",
      "/elden-ring-screenshot-3.jpg",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    status: "pending",
    submittedDate: "2024-10-12",
    fileSize: "48.5 GB",
    price: "799.000đ",
    minimumRequirements: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i5-8400",
      memory: "12 GB RAM",
      graphics: "NVIDIA GTX 1060",
      storage: "60 GB SSD",
    },
  },
  {
    id: 5,
    title: "Stardew Valley",
    developer: "ConcernedApe",
    publisher: "ConcernedApe",
    releaseDate: "2016-02-26",
    genre: ["Simulation", "RPG", "Casual"],
    platform: ["PC", "Nintendo Switch", "PlayStation 4", "Mobile"],
    rating: 4.8,
    description:
      "Build the farm of your dreams, raise animals, grow crops, and build relationships in the peaceful town of Stardew Valley.",
    coverImage: "/stardew-valley-game-cover.jpg",
    screenshots: [
      "/stardew-valley-screenshot-1.jpg",
      "/stardew-valley-screenshot-2.jpg",
      "/stardew-valley-screenshot-3.jpg",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    status: "approved",
    submittedDate: "2024-09-25",
    fileSize: "500 MB",
    price: "99.000đ",
    minimumRequirements: {
      os: "Windows 7 or later",
      processor: "Intel Core 2 Duo E4400",
      memory: "4 GB RAM",
      graphics: "Intel HD Graphics 3000",
      storage: "1 GB HDD",
    },
  },
  {
    id: 6,
    title: "The Last of Us Part I",
    developer: "Naughty Dog",
    publisher: "Sony Interactive Entertainment",
    releaseDate: "2023-03-28",
    genre: ["Action", "Adventure", "Drama"],
    platform: ["PC", "PlayStation 5"],
    rating: 4.9,
    description:
      "Experience the emotional storytelling and unforgettable characters of The Last of Us, rebuilt for a new generation with modernized gameplay and enhanced visuals.",
    coverImage: "/the-last-of-us-game-cover.jpg",
    screenshots: [
      "/the-last-of-us-screenshot-1.jpg",
      "/the-last-of-us-screenshot-2.jpg",
      "/the-last-of-us-screenshot-3.jpg",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    status: "rejected",
    submittedDate: "2024-10-22",
    fileSize: "70 GB",
    price: "899.000đ",
    minimumRequirements: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i7-8700",
      memory: "16 GB RAM",
      graphics: "NVIDIA RTX 2060",
      storage: "100 GB SSD",
    },
  },
]
